import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const {data: user} = api.user.getLatest.useQuery()
  
  if(!user){
    return <span>loading...</span>
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
        
          <p className="">
            Latest user:
            {user && (
              <span>
                {`${user.name}, Created: ${user.createdAt.toString()}`}
              </span>
            )}
          </p>
        </div>
      </main>
    </>
  );
}
